[logger]

# Level of logging: 'error', 'warning', 'info', or 'debug'.

# Default: 'info'
level = "info"

# String format for logging messages. If logger.datetimeFormat is set,
# logger messages will default to `%(asctime)s.%(msecs)03d %(message)s`. See
# Python's documentation for available attributes:
# https://docs.python.org/2.6/library/logging.html#formatter-objects

# Default: "%(asctime)s %(message)s"
messageFormat = "%(asctime)s %(message)s"


[client]

# Whether to enable st.cache. This does not affect st.cache_data or
# st.cache_resource.

# Default: true
caching = true

# If false, makes your Streamlit script not draw to a
# Streamlit app.

# Default: true
displayEnabled = true


[server]
runOnSave = true



[theme]
font="sans serif"
base="dark"
primaryColor="#6b7cfb"
backgroundColor="#1a2539"
secondaryBackgroundColor="#394352"
